/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as DndSpellsRouteImport } from './routes/dnd-spells'
import { Route as DndMonstersRouteImport } from './routes/dnd-monsters'
import { Route as DndItemsRouteImport } from './routes/dnd-items'
import { Route as DndClassesRouteImport } from './routes/dnd-classes'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiNewRouteImport } from './routes/wiki.new'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as WikiSlugHistoryRouteImport } from './routes/wiki.$slug.history'
import { Route as WikiSlugEditRouteImport } from './routes/wiki.$slug.edit'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const DndSpellsRoute = DndSpellsRouteImport.update({
  id: '/dnd-spells',
  path: '/dnd-spells',
  getParentRoute: () => rootRouteImport,
} as any)
const DndMonstersRoute = DndMonstersRouteImport.update({
  id: '/dnd-monsters',
  path: '/dnd-monsters',
  getParentRoute: () => rootRouteImport,
} as any)
const DndItemsRoute = DndItemsRouteImport.update({
  id: '/dnd-items',
  path: '/dnd-items',
  getParentRoute: () => rootRouteImport,
} as any)
const DndClassesRoute = DndClassesRouteImport.update({
  id: '/dnd-classes',
  path: '/dnd-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiNewRoute = WikiNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WikiRoute,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WikiRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugHistoryRoute = WikiSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugEditRoute = WikiSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WikiSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/contributors': typeof ContributorsRoute
  '/dnd-classes': typeof DndClassesRoute
  '/dnd-items': typeof DndItemsRoute
  '/dnd-monsters': typeof DndMonstersRoute
  '/dnd-spells': typeof DndSpellsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki': typeof WikiRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/new': typeof WikiNewRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/contributors': typeof ContributorsRoute
  '/dnd-classes': typeof DndClassesRoute
  '/dnd-items': typeof DndItemsRoute
  '/dnd-monsters': typeof DndMonstersRoute
  '/dnd-spells': typeof DndSpellsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/u/$username': typeof UUsernameRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/new': typeof WikiNewRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/contributors': typeof ContributorsRoute
  '/dnd-classes': typeof DndClassesRoute
  '/dnd-items': typeof DndItemsRoute
  '/dnd-monsters': typeof DndMonstersRoute
  '/dnd-spells': typeof DndSpellsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki': typeof WikiRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/new': typeof WikiNewRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/campaigns'
    | '/contributors'
    | '/dnd-classes'
    | '/dnd-items'
    | '/dnd-monsters'
    | '/dnd-spells'
    | '/resources'
    | '/settings'
    | '/sitemap.xml'
    | '/wiki'
    | '/u/$username'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/wiki/'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/campaigns'
    | '/contributors'
    | '/dnd-classes'
    | '/dnd-items'
    | '/dnd-monsters'
    | '/dnd-spells'
    | '/resources'
    | '/settings'
    | '/sitemap.xml'
    | '/u/$username'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/wiki'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/campaigns'
    | '/contributors'
    | '/dnd-classes'
    | '/dnd-items'
    | '/dnd-monsters'
    | '/dnd-spells'
    | '/resources'
    | '/settings'
    | '/sitemap.xml'
    | '/wiki'
    | '/u/$username'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/wiki/'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  ContributorsRoute: typeof ContributorsRoute
  DndClassesRoute: typeof DndClassesRoute
  DndItemsRoute: typeof DndItemsRoute
  DndMonstersRoute: typeof DndMonstersRoute
  DndSpellsRoute: typeof DndSpellsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WikiRoute: typeof WikiRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd-spells': {
      id: '/dnd-spells'
      path: '/dnd-spells'
      fullPath: '/dnd-spells'
      preLoaderRoute: typeof DndSpellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd-monsters': {
      id: '/dnd-monsters'
      path: '/dnd-monsters'
      fullPath: '/dnd-monsters'
      preLoaderRoute: typeof DndMonstersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd-items': {
      id: '/dnd-items'
      path: '/dnd-items'
      fullPath: '/dnd-items'
      preLoaderRoute: typeof DndItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd-classes': {
      id: '/dnd-classes'
      path: '/dnd-classes'
      fullPath: '/dnd-classes'
      preLoaderRoute: typeof DndClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/new': {
      id: '/wiki/new'
      path: '/new'
      fullPath: '/wiki/new'
      preLoaderRoute: typeof WikiNewRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof WikiRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/history': {
      id: '/wiki/$slug/history'
      path: '/history'
      fullPath: '/wiki/$slug/history'
      preLoaderRoute: typeof WikiSlugHistoryRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/edit': {
      id: '/wiki/$slug/edit'
      path: '/edit'
      fullPath: '/wiki/$slug/edit'
      preLoaderRoute: typeof WikiSlugEditRouteImport
      parentRoute: typeof WikiSlugRoute
    }
  }
}

interface WikiSlugRouteChildren {
  WikiSlugEditRoute: typeof WikiSlugEditRoute
  WikiSlugHistoryRoute: typeof WikiSlugHistoryRoute
}

const WikiSlugRouteChildren: WikiSlugRouteChildren = {
  WikiSlugEditRoute: WikiSlugEditRoute,
  WikiSlugHistoryRoute: WikiSlugHistoryRoute,
}

const WikiSlugRouteWithChildren = WikiSlugRoute._addFileChildren(
  WikiSlugRouteChildren,
)

interface WikiRouteChildren {
  WikiSlugRoute: typeof WikiSlugRouteWithChildren
  WikiNewRoute: typeof WikiNewRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiSlugRoute: WikiSlugRouteWithChildren,
  WikiNewRoute: WikiNewRoute,
  WikiIndexRoute: WikiIndexRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  ContributorsRoute: ContributorsRoute,
  DndClassesRoute: DndClassesRoute,
  DndItemsRoute: DndItemsRoute,
  DndMonstersRoute: DndMonstersRoute,
  DndSpellsRoute: DndSpellsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WikiRoute: WikiRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
